### ISSUE TITLE
How to transfer tokens without seeing the contract?

### ISSUE THREAD

**Issue by FredBah** [vittominacori/token-generator#8]
So I created some simple tokens on Rinkeby testnet.  I see the contract, but how do i "play" with the tokens when the contract is not verified and published?

**Comment by vittominacori** [comment]
Hi, contracts are automatically verified on mainnet but not on testnet. 
You can copy ABI from https://vittominacori.github.io/erc20-generator/docs/ and import in aome tools like MyEtherWallet in order to play.
When you go live on mainnet your code will be verified and you can use it from etherscan too.
